
FROM n8nio/n8n

ENV GENERIC_TIMEZONE="America/Sao_Paulo"
ENV N8N_BASIC_AUTH_ACTIVE=false
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=db
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=gastos
ENV DB_POSTGRESDB_USER=postgres
ENV DB_POSTGRESDB_PASSWORD=postgres
ENV N8N_PORT=5678
EXPOSE 5678
